### PR TITLE
[TASK] Increases verbose output when debugging (-vvv) is set

### PR DESCRIPTION
**Pull request by garvinhicking**
To debug https://github.com/TYPO3-Documentation/render-guides/issues/83 we need more verbose output what directories/files are used.

This depends on https://github.com/phpDocumentor/guides/pull/705

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
We should then also decrease the `-vvv` when running `make docs` to `-vv` to avoid that much noise when running the guides command.

**Comment by garvinhicking** [comment]
> We should then also decrease the `-vvv` when running `make docs` to `-vv` to avoid that much noise when running the guides command.

Yes - however, we'll first need to have it enabled, because this debugging is required to see why the github-render-action fails to properly configure a project. Or we need a way to specify "-vvv" for a github action, but a problem is that I can only see how to add options with two dashes to a github action and a specifiy name, not with a single dash - see https://github.com/phpDocumentor/guides/pull/705#issuecomment-1822936243

**Comment by brotkrueml** [comment]
> > We should then also decrease the `-vvv` when running `make docs` to `-vv` to avoid that much noise when running the guides command.
> 
> Yes - however, we'll first need to have it enabled, because this debugging is required to see why the github-render-action fails to properly configure a project. Or we need a way to specify "-vvv" for a github action, but a problem is that I can only see how to add options with two dashes to a github action and a specifiy name, not with a single dash - see [phpDocumentor/guides#705 (comment)](https://github.com/phpDocumentor/guides/pull/705#issuecomment-1822936243)

Well, instead of using "make docs" in the action you can use the full command with "-vvv" (also for locally debugging). Debug information which is not needed locally on rendering most of the time can make warnings hard to recognise.

**Comment by garvinhicking** [comment]
> Well, instead of using "make docs" in the action you can use the full command with "-vvv" (also for locally debugging). Debug information which is not needed locally on rendering most of the time can make warnings hard to recognise.
> 
> Or add a "make docs-debug" option for convenience.

Please check out the YAML of the github action. There's no make file being run, but an entrypoint of the docker image, and arguments are passed differently... not sure how to proceed here.

**Comment by brotkrueml** [comment]
> Please check out the YAML of the github action. There's no make file being run, but an entrypoint of the docker image, and arguments are passed differently... not sure how to proceed here.

Yup, but that does not invalidate my remark about the Makefile:
https://github.com/TYPO3-Documentation/render-guides/blob/main/Makefile#L67

**Comment by garvinhicking** [comment]
> Yup, but that does not invalidate my remark about the Makefile: https://github.com/TYPO3-Documentation/render-guides/blob/main/Makefile#L67

Just to flesh this out:

* First we need to figure out a way to add toggle-able debug output to https://github.com/phpDocumentor/guides/pull/705 (I don't know how)
* Once that is done, we need to merge both PRs
* Then we need to run the github action and see why the rendering fails to recognize guides.xml (which needs the -vvv of the makefile)
* Once we figured this out, we remove the extra verbosity from the command of this repository (Makefile) (and may need to re-enable it if we face further issues with the docker image)

The best way of course would be to be able to pass verbosity commands to the github workflow, then we could directly remove the "-vvv" from the default Makefile command.

Looking forward to ideas/input/help, I believe Jaapio offered to check into it when there's time!

**Review by brotkrueml — APPROVED** [review]

**Comment by brotkrueml** [comment]
As the adaption of the Makefile can also be done later, approved.

**Pull request merged**
