### PR TITLE
[FEATURE] add configure command adjust config

### PR DESCRIPTION
**Pull request by jaapio**

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
I would prefer to add a description to the command which explains what it does. What do you think?

**Comment by jaapio** [comment]
Yes, that should be added, I have some more plans with this command. Like setting up the default config and directory structure.

**Comment by garvinhicking** [comment]
I continued this here and added it into our toolbox:

https://github.com/TYPO3-Documentation/render-guides/commit/9d07b3219817da9b0859b1849e3da982c6f4b87a

**Comment by garvinhicking** [comment]
Closing with the recent changes this is adressed.

**Pull request closed without merging**
