### PR TITLE
[FEATURE] List available standard inventories

### PR DESCRIPTION
**Pull request by linawolf**
They can be documented by using directive ..  guides:inventories::

Resolves https://github.com/TYPO3-Documentation/render-guides/issues/373

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
Is there somehow the possibility to describe the inventories? For example, "t3install" is the "Upgrade Guide" and not the "Installation Guide". Maybe a method in the enum which returns the descriptions?

**Comment by linawolf** [comment]
It is possible if we have the descriptions in the enum. Or we could just fetch all the inventories and get the title of the "start" reference...

**Comment by brotkrueml** [comment]
As the inventories are already explicitely defined in the enum I think defining a method would be the easiest way. Otherwise all repos must by fetched by suspicion upon rendering, or only when the directive is used - both has an unnecessary overhead as this directive is only used in ony place, I assume.

**Review by garvinhicking — APPROVED** [review]
Very cool, thanks! We could address descriptions in a follow-up? That's a good idea too!

**Pull request merged**
