### PR TITLE
[TASK] Remove usage of _static/ajax-version-hints.html in version selector

### PR DESCRIPTION
**Pull request by brotkrueml**
This file is not available on docs.typo3.org for Sphinx-rendered manuals. For local rendering with Sphinx the file is empty. So the code around this file serves no obvious purpose and is therefore removed.

### CODE REVIEW

**Review by linawolf — APPROVED** [review]
Please re-run ddev gulp build to resolve the conflicts

**Comment by brotkrueml** [comment]
> There still appear to be conflicts

Where do you see them? I merged main into the branch and regenerated the minified JS file.

**Comment by linawolf** [comment]
image

**Comment by brotkrueml** [comment]
I don't see that. Everything's green here.

**Pull request merged**
