### PR TITLE
[FEATURE] Prev/Next links

### PR DESCRIPTION
**Pull request by linawolf**
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/35

### CODE REVIEW

**Comment by garvinhicking** [comment]
Wow, great work. Hard to review on mobile due to many markup changes.

I should find some time on friday to check it out, tomorrow I'm swamped.

**Comment by linawolf** [comment]
Good point! I think I was able to eliminate some of the layout changes

**Comment by garvinhicking** [comment]
When I build the "Documentation" from the repository, if I go to a subdirectory like "Documentation/Developer" from the rendered HTML, the links of next/prev duplicate the directory structure. 

So the HTML is opened inside Documentation/Developer/ and the link leads to "Developer/Contributing.html" - thus, the browser will resolve the link to "Documentation/Developer/Developer/Contributing.html".

I suppose if more subdirectories are involved, there will be doubling of the full path, i.e. "A/B/C/index.html" with a link to "A/B/C/D/index.html" would point to "/A/B/C/A/B/C/D/index.html"

**Comment by linawolf** [comment]
This is an unrealated problem, we seem to have a general issue with no relative links being generated in the Documentation folder.

**Comment by brotkrueml** [comment]
@linawolf Please resolve the conflicts first.

**Comment by linawolf** [comment]
@brotkrueml I rebased and now less files are changed as all the partly tests are not affected

**Comment by garvinhicking** [comment]
With current version I sadly still have the issue that the prev/next navigation does not show the proper linear navigation chain. I believe this is caused by another issue?

IMO we should first solve that issue properly, then rebase, and then approach this prev/next feature? Or maybe fix the proper ordering within this feature branch?

**Comment by garvinhicking** [comment]
(Addendum: The relative links now are fixed though, PREV/NEXT does not mangle this anymore for me)

**Comment by jaapio** [comment]
I think this PR will benefit from: https://github.com/phpDocumentor/guides/pull/682

**Comment by linawolf** [comment]
I would suggest, we merge this as-is and make a follow up, once https://github.com/phpDocumentor/guides/pull/682 is merged. What do you think @garvinhicking ?

**Comment by garvinhicking** [comment]
I would agree, yes @linawolf - if that's ok woth @brotkrueml too of course!

**Review by garvinhicking — APPROVED** [review]

**Pull request merged**
