### PR TITLE
[TASK] Add tests for the new improved menu

### PR DESCRIPTION
**Pull request by linawolf**
* Menu depth can now be limited by setting `max-menu-depth="1"`
* Main menu is calculated once during compiling instead of for each page during rendering
* `:maxdepth: 1` on the toctree does not limit the main menu anymore (just like in Sphinx)

### CODE REVIEW

**Comment by brotkrueml** [comment]
So, max-menu-depth is a new guides attribute? I am missing the context in the attribute or is this setting considered for every menu (like also tocs for a page)?

**Comment by linawolf** [comment]
Yes it is a new setting in the guides, feel free to propose a better name there.

It limits the global menu stored in the project node.

**Comment by brotkrueml** [comment]
Why do we have then tests for it? Shouldn't they be in guides?

**Comment by linawolf** [comment]
They are but as these functionalities are important to us I want to make sure, we don't break them. I didnt add all tests but just two cases. They are test-cases that would not have worked until now

**Comment by brotkrueml** [comment]
Seems, you have little confidence in the guides tests ;-)

**Review by brotkrueml — APPROVED** [review]

**Comment by linawolf** [comment]
I do have confidence in the guides tests. But everything the guides do is overridable in multiple ways. So we might break something that works in the guides.

**Pull request merged**
