### PR TITLE
[TASK] Add Basic Styling for Code-Block Caption

### PR DESCRIPTION
**Pull request by linawolf**
We can discuss in a follow up weather we want to include additional information like the icons proposed here: https://github.com/TYPO3-Documentation/render-guides/pull/310

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
For me it is too less contrast and distinction between the caption and the code:

Bildschirmfoto vom 2024-01-26 17-55-23

Would like to have a better separation.

**Comment by linawolf** [comment]
We could use the url-bar like background from my other PR again:

image

**Comment by brotkrueml** [comment]
Hmm, contrast still too less.

Maybe we should use a dark separator line below the caption. But I assume that won't look good.

**Comment by garvinhicking** [comment]
I agree, this is a bit too light and doesn't set off enough. How about either a clear dark border, or a dark box with light text (inverted so to say)? I do think box caption could structurize the perception of sections so clear lines or boxes would be good?

**Comment by linawolf** [comment]
With a shadow maybe?

image

**Comment by garvinhicking** [comment]
(On it with an idea on how to proceed)

**Comment by linawolf** [comment]
solved in a follow up

**Pull request closed without merging**
