### PR TITLE
[TASK] Update codehighlight library to version 0.1.0

### PR DESCRIPTION
**Pull request by brotkrueml**

### CODE REVIEW

**Review by linawolf — APPROVED** [review]

**Comment by linawolf** [comment]
Please have a look at the tests

**Comment by brotkrueml** [comment]
Argh, the scrollbar hides that... has a look before ...

**Comment by brotkrueml** [comment]
@linawolf We have another problem:

    Problem 1
    - Root composer.json requires t3docs/typo3-version-handling, it could not be found in any version, there may be a typo in the package name.


The t3docs/typo3-version-handling is not on Packagist. This has to be solved first.

**Comment by linawolf** [comment]
> The t3docs/typo3-version-handling is not on Packagist. This has to be solved first.

Taking care of it now

**Review by linawolf — APPROVED** [review]

**Review by garvinhicking — APPROVED** [review]

**Pull request merged**
