### PR TITLE
[TASK] Revise "menu-expandable.js"

### PR DESCRIPTION
**Pull request by brotkrueml**
- Embed logic into self-executing function so no details are leaked into global space
- Use modern JavaScript constructs like "const" and "forEach"
- Remove usage of jQuery

### CODE REVIEW

**Review by linawolf — COMMENTED** [review]
Where you able to test this without the menus properly working in HTML?

**Review by linawolf — APPROVED** [review]
'I guess if nessecary we can make a follow up after subsequent HTMl chagnes

**Comment by brotkrueml** [comment]
> Where you able to test this without the menus properly working in HTML?

Yup, I faked them by tweaking the template to always show "current". Also checked with a page called "TYPO3 Exceptions".

**Comment by brotkrueml** [comment]
> 'I guess if nessecary we can make a follow up after subsequent HTMl chagnes

Yup, of course. The current structure (CSS classes and selectors) is not nice.

**Pull request merged**
