### PR TITLE
[TASK] Refine TypoScript highlighting

### PR DESCRIPTION
**Pull request by brotkrueml**
- Remove number recognition as it has no real value
- Add missing keywords
- Enhance path recognition
- Handle constants (`{$foo.bar}`)
- Distinct between RGB color and comments (`#000` and `#000000`)
- Distinct between SQL quotes and comments ('#fieldname')
- Add tests

### CODE REVIEW

**Review by linawolf — APPROVED** [review]
While you are at it, I would recommend to make comment detection more strict: 

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/TypoScript/Syntax/Comments/Index.html

// and # indicate a comment. Everything until the end of the line will be ignored by the parser. /* indicates a multiline comment start, */ stops it.

When using //, # and /* after an assignment =, this is not considered a comment, but part of the value! Same is true for multiline assignments.

**Comment by brotkrueml** [comment]
Hmm, may be a possibility, but we have than to take care it is non-greedy. But we are talking here about highlighting in the docs. And I can't think of an example, where we use a multi-line comment with an invalid part after the closing comment part.

**Comment by linawolf** [comment]
In TypoScript we do not support the the partly commenting of a line. The whole line is either a comment or not

So for one liner comments you can catch them by `^\n*#`

**Comment by brotkrueml** [comment]
> In TypoScript we do not support the the partly commenting of a line. The whole line is either a comment or not
> 
> So for one liner comments you can catch them by `^\n*#`

This is not true:

    foo < bar // This is a comment
    foo < bar /* This is a valid comment, too */

    foo > # Another valid comment

    foo := addToList(1) # Yes, a comment

    [foo = bar] # Many comment. Much wow.

    foo (
      # This is NOT a comment but part of the value assignment!
      bar = barValue
    ) # This is a comment

**Comment by brotkrueml** [comment]
Okay, don't get the regexp so this one does not match:

    foo = bar // This is NOT a comment but part of the value assignment!

but this one:

    foo // This is a comment

Tried the negative lookbehind assertion but that doesn't work. Also some other possibilities. Will skip.

**Pull request merged**
